
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://35.239.87.114:5432/ticket}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticket_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.default_schema=${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:public}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin}


jwt.secret=${JWT_SECRET:change-this-secret-before-production}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:25MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:30MB}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


app.base-url=${APP_BASE_URL:http://localhost:3000}

# SMTP config (example: Gmail App Password)
spring.mail.host=${SPRING_MAIL_HOST:}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.health.mail.enabled=${MANAGEMENT_HEALTH_MAIL_ENABLED:false}

# Data initialization (loads data.sql automatically)
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
